trigger: none
pr: none

schedules:
  - cron: '0 0 * * *'
    displayName: Daily builds
    branches:
      include:
        - main
    always: true

resources:
  repositories:
    - repository: 1ESPipelineTemplates
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release

extends:
  template: v1/1ES.Unofficial.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: Azure-Pipelines-1ESPT-ExDShared
      os: linux
    stages:
      - stage: Build
        jobs:
          - job: Build
            displayName: Build PHP SDK
            steps:
              - checkout: self
                submodules: recursive

              - script: sudo apt-get update && sudo apt-get install -y php php-xml php-mbstring php-curl unzip
                displayName: Install PHP

              - script: |
                  php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
                  php composer-setup.php --install-dir=/usr/local/bin --filename=composer
                displayName: Install Composer

              - script: composer install --no-interaction --prefer-dist
                displayName: Install dependencies
                workingDirectory: $(Build.SourcesDirectory)

              - script: vendor/bin/phpunit
                displayName: Run unit tests
                workingDirectory: $(Build.SourcesDirectory)
