# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

name: "bump sdk version"


on:
  push:
    branches:
      - "v1.0/pipelinebuild/*"
      - "beta/pipelinebuild/*"
    paths:
      - 'src/Model/**'
      - 'src/*/Model/**'
      - 'src/Beta/**'

defaults:
  run:
    shell: bash

jobs:
  bump-sdk-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Git config user
      run: |
        git config --global user.email "GraphTooling@service.microsoft.com"
        git config --global user.name "Microsoft Graph DevX Tooling"
    - name: Run increment script
      run: php scripts/BumpStableSdkVersion.php

    - name: Commit and push changes if any
      run: if git commit -am "Bump SDK version"; then git push origin $GITHUB_REF; fi
